name: Sync to fenix-website-oficial

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to oficial repo
        run: |
          git remote add oficial https://x-access-token:${{ secrets.GH_PAT }}@github.com/JaimeCombita/fenix-website-oficial.git
          git push oficial main:main --force
